In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:


df = pd.read_csv(
    r"C:\Users\ASUS\OneDrive\Desktop\Ecommerce-Sales-Profitability-Analysis\data\raw\ecommerce_orders_dataset.csv"
)

df.head()

,Order_ID,Customer_ID,Order_Date,Year,Month,Day,Day_Of_Week,Quarter,Customer_Age,Customer_Gender,...,Delivery_Days,Order_Status,Returned,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount,Season,Holiday_Season,High_Value_Order
0,615717,CUST007322,2023-01-01,2023,1,1,Sunday,1,32,Male,...,2,Delivered,No,4.4,2144.92,23.10,15.75,Winter,No,No
1,626919,CUST004717,2023-01-01,2023,1,1,Sunday,1,50,Male,...,9,Delivered,No,4.1,817.17,8.57,3.32,Winter,No,No
2,615781,CUST004415,2023-01-01,2023,1,1,Sunday,1,61,Male,...,2,Delivered,No,5.0,541.16,29.72,45.67,Winter,No,No
3,621747,CUST004114,2023-01-01,2023,1,1,Sunday,1,34,Male,...,6,Returned,Yes,3.4,700.49,25.22,75.25,Winter,No,No
4,625881,CUST000145,2023-01-01,2023,1,1,Sunday,1,37,Male,...,8,Delivered,No,3.6,2133.77,24.64,26.06,Winter,No,No

In [38]:
clean_df = df.copy()

In [39]:
clean_df.dtypes

Order_ID                     int64
Customer_ID                 object
Order_Date                  object
Year                         int64
Month                        int64
Day                          int64
Day_Of_Week                 object
Quarter                      int64
Customer_Age                 int64
Customer_Gender             object
Country                     object
City                        object
Customer_Segment            object
Product_ID                  object
Product_Category            object
Product_Subcategory         object
Brand                       object
Unit_Price                 float64
Quantity                     int64
Discount_Percent             int64
Discount_Amount            float64
Coupon_Used                 object
Shipping_Cost              float64
Tax_Amount                 float64
Order_Amount               float64
Payment_Method              object
Device_Type                 object
Traffic_Source              object
Membership_Status           object
Shipping_Method             object
Warehouse_Region            object
Delivery_Days                int64
Order_Status                object
Returned                    object
Review_Rating              float64
Customer_Lifetime_Value    float64
Profit_Margin_Percent      float64
Profit_Amount              float64
Season                      object
Holiday_Season              object
High_Value_Order            object
dtype: object

In [40]:
clean_df["Order_Date"].head()

0    2023-01-01
1    2023-01-01
2    2023-01-01
3    2023-01-01
4    2023-01-01
Name: Order_Date, dtype: object

In [41]:
clean_df["Order_Date"] = pd.to_datetime(clean_df["Order_Date"])

In [42]:
clean_df["Order_Date"].dtype

dtype('<M8[ns]')

In [43]:
clean_df.isnull().sum()

Order_ID                   0
Customer_ID                0
Order_Date                 0
Year                       0
Month                      0
Day                        0
Day_Of_Week                0
Quarter                    0
Customer_Age               0
Customer_Gender            0
Country                    0
City                       0
Customer_Segment           0
Product_ID                 0
Product_Category           0
Product_Subcategory        0
Brand                      0
Unit_Price                 0
Quantity                   0
Discount_Percent           0
Discount_Amount            0
Coupon_Used                0
Shipping_Cost              0
Tax_Amount                 0
Order_Amount               0
Payment_Method             0
Device_Type                0
Traffic_Source             0
Membership_Status          0
Shipping_Method            0
Warehouse_Region           0
Delivery_Days              0
Order_Status               0
Returned                   0
Review_Rating              0
Customer_Lifetime_Value    0
Profit_Margin_Percent      0
Profit_Amount              0
Season                     0
Holiday_Season             0
High_Value_Order           0
dtype: int64

In [44]:
clean_df.isnull().sum().sum()

0

In [45]:
clean_df.duplicated().sum()

0

In [46]:
clean_df.describe().T

,count,mean,min,25%,50%,75%,max,std
Order_ID,30000.0,615000.5,600001.0,607500.75,615000.5,622500.25,630000.0,8660.398374
Order_Date,30000,2024-12-29 10:37:23.520000,2023-01-01 00:00:00,2023-12-27 18:00:00,2024-12-30 00:00:00,2025-12-29 00:00:00,2026-12-31 00:00:00,NaN
Year,30000.0,2024.4947,2023.0,2023.0,2024.0,2025.0,2026.0,1.118815
Month,30000.0,6.5315,1.0,4.0,7.0,10.0,12.0,3.460955
Day,30000.0,15.7236,1.0,8.0,16.0,23.0,31.0,8.779714
Quarter,30000.0,2.507,1.0,2.0,3.0,4.0,4.0,1.118806
Customer_Age,30000.0,36.3703,18.0,28.0,36.0,44.0,75.0,11.315534
Unit_Price,30000.0,126.820148,3.84,29.88,60.67,128.5725,1940.0,172.675272
Quantity,30000.0,3.080667,1.0,2.0,3.0,4.0,11.0,1.450412
Discount_Percent,30000.0,12.618667,0.0,0.0,10.0,20.0,40.0,11.085201
Discount_Amount,30000.0,49.432742,0.0,0.0,13.47,44.8225,2623.9,114.401634
Shipping_Cost,30000.0,10.316779,0.0,6.02,9.0,14.22,32.6,5.890701
Tax_Amount,30000.0,29.143818,0.26,5.27,12.065,29.4425,1043.16,49.562251
Order_Amount,30000.0,379.001466,6.67,82.9475,171.03,388.19,10314.27,585.405554
Delivery_Days,30000.0,4.436667,0.0,3.0,4.0,6.0,13.0,2.349363
Review_Rating,30000.0,4.04799,1.0,3.6,4.1,4.6,5.0,0.686492
Customer_Lifetime_Value,30000.0,4372.340178,20.0,1029.6375,2073.365,4482.105,50000.0,6811.029394
Profit_Margin_Percent,30000.0,21.969056,3.0,15.68,21.87,28.18,56.61,9.079134
Profit_Amount,30000.0,73.863876,0.27,16.64,36.995,82.125,2480.54,113.480736

In [47]:
clean_df["Product_Category"].unique()

array(['Books', 'Sports', 'Beauty', 'Fashion', 'Home & Kitchen',
       'Groceries', 'Electronics', 'Toys'], dtype=object)

In [48]:
clean_df["Customer_Segment"].unique()

array(['Loyal', 'Returning', 'Premium', 'New'], dtype=object)

In [49]:
clean_df["Order_Status"].unique()

array(['Delivered', 'Returned', 'Processing', 'Shipped', 'Cancelled'],
      dtype=object)

In [50]:
clean_df["Payment_Method"].unique()

array(['Debit Card', 'Wallet', 'Cash on Delivery', 'PayPal',
       'Credit Card', 'Bank Transfer'], dtype=object)

In [51]:
print("Negative quantities:", (clean_df["Quantity"] < 0).sum())
print("Negative unit prices:", (clean_df["Unit_Price"] < 0).sum())
print("Negative order amounts:", (clean_df["Order_Amount"] < 0).sum())
print("Negative discounts:", (clean_df["Discount_Percent"] < 0).sum())
print("Negative shipping costs:", (clean_df["Shipping_Cost"] < 0).sum())

Negative quantities: 0
Negative unit prices: 0
Negative order amounts: 0
Negative discounts: 0
Negative shipping costs: 0

In [52]:
print("Loss-making orders:", (clean_df["Profit_Amount"] < 0).sum())
print("Profitable orders:", (clean_df["Profit_Amount"] > 0).sum())
print("Zero-profit orders:", (clean_df["Profit_Amount"] == 0).sum())

Loss-making orders: 0
Profitable orders: 30000
Zero-profit orders: 0

In [53]:
clean_df["Year"].eq(clean_df["Order_Date"].dt.year).value_counts()

True    30000
Name: count, dtype: int64

In [54]:
clean_df["Month"].eq(clean_df["Order_Date"].dt.month).value_counts()

True    30000
Name: count, dtype: int64

In [55]:
clean_df["Day"].eq(clean_df["Order_Date"].dt.day).value_counts()

True    30000
Name: count, dtype: int64

In [56]:
clean_df["Quarter"].eq(clean_df["Order_Date"].dt.quarter).value_counts()

True    30000
Name: count, dtype: int64

In [57]:
print("Negative Quantity:",
      (clean_df["Quantity"] < 0).sum())

print("Negative Unit Price:",
      (clean_df["Unit_Price"] < 0).sum())

print("Negative Order Amount:",
      (clean_df["Order_Amount"] < 0).sum())

print("Negative Discount:",
      (clean_df["Discount_Percent"] < 0).sum())

print("Negative Shipping Cost:",
      (clean_df["Shipping_Cost"] < 0).sum())

print("Negative Tax Amount:",
      (clean_df["Tax_Amount"] < 0).sum())

Negative Quantity: 0
Negative Unit Price: 0
Negative Order Amount: 0
Negative Discount: 0
Negative Shipping Cost: 0
Negative Tax Amount: 0

In [58]:
print("Discount range:",
      clean_df["Discount_Percent"].min(),
      "to",
      clean_df["Discount_Percent"].max())

print("Profit Margin range:",
      clean_df["Profit_Margin_Percent"].min(),
      "to",
      clean_df["Profit_Margin_Percent"].max())

Discount range: 0 to 40
Profit Margin range: 3.0 to 56.61

In [59]:
print("Review Rating range:",
      clean_df["Review_Rating"].min(),
      "to",
      clean_df["Review_Rating"].max())

Review Rating range: 1.0 to 5.0

In [60]:
categorical_columns = [
    "Customer_Gender",
    "Customer_Segment",
    "Product_Category",
    "Product_Subcategory",
    "Coupon_Used",
    "Order_Status",
    "Payment_Method",
    "Season",
    "Holiday_Season",
    "High_Value_Order"
]

for col in categorical_columns:
    print("\n", col)
    print(clean_df[col].value_counts())

 Customer_Gender
Customer_Gender
Female    14863
Male      14552
Other       585
Name: count, dtype: int64

 Customer_Segment
Customer_Segment
Returning    11987
New           7794
Loyal         7214
Premium       3005
Name: count, dtype: int64

 Product_Category
Product_Category
Fashion           6092
Groceries         5380
Electronics       4699
Home & Kitchen    4194
Beauty            2971
Sports            2439
Books             2163
Toys              2062
Name: count, dtype: int64

 Product_Subcategory
Product_Subcategory
Men Clothing      1591
Women Clothing    1515
Bags              1497
Shoes             1489
Beverages         1385
Snacks            1381
Dairy             1317
Fresh Produce     1297
Mobile            1216
Laptop            1171
Accessories       1167
Headphones        1145
Furniture         1063
Cookware          1062
Decor             1036
Appliances        1033
Haircare           769
Fragrance          755
Skincare           738
Makeup             709
Fitness            639
Equipment          605
Outdoor            599
Sportswear         596
Comics             558
Fiction            555
Educational        555
Education          540
Non-Fiction        510
Puzzles            507
Action Figures     503
Board Games        497
Name: count, dtype: int64

 Coupon_Used
Coupon_Used
Yes    20429
No      9571
Name: count, dtype: int64

 Order_Status
Order_Status
Delivered     19497
Shipped        3469
Returned       3033
Processing     2230
Cancelled      1771
Name: count, dtype: int64

 Payment_Method
Payment_Method
Credit Card         5080
PayPal              5006
Bank Transfer       5002
Wallet              4977
Debit Card          4969
Cash on Delivery    4966
Name: count, dtype: int64

 Season
Season
Summer    7575
Winter    7534
Spring    7519
Autumn    7372
Name: count, dtype: int64

 Holiday_Season
Holiday_Season
No     25550
Yes     4450
Name: count, dtype: int64

 High_Value_Order
High_Value_Order
No     22499
Yes     7501
Name: count, dtype: int64

In [61]:
clean_df["Profit_Amount"].describe()

count    30000.000000
mean        73.863876
std        113.480736
min          0.270000
25%         16.640000
50%         36.995000
75%         82.125000
max       2480.540000
Name: Profit_Amount, dtype: float64

In [62]:
print("Loss-making orders:",
      (clean_df["Profit_Amount"] < 0).sum())

print("Profitable orders:",
      (clean_df["Profit_Amount"] > 0).sum())

print("Zero-profit orders:",
      (clean_df["Profit_Amount"] == 0).sum())

Loss-making orders: 0
Profitable orders: 30000
Zero-profit orders: 0

In [63]:
"C:\Users\ASUS\OneDrive\Desktop\Ecommerce-Sales-Profitability-Analysis"

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3745542221.py, line 1)

In [ ]:
import os

# Create the cleaned folder if it doesn't exist
os.makedirs(
    r"C:\Users\ASUS\OneDrive\Desktop\Ecommerce-Sales-Profitability-Analysis\data\cleaned",
    exist_ok=True
)

# Save the cleaned dataset
clean_df.to_csv(
    r"C:\Users\ASUS\OneDrive\Desktop\Ecommerce-Sales-Profitability-Analysis\data\cleaned\ecommerce_orders_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!