In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
import os
import shutil

# Your project folder
project_path = r"C:\Users\ASUS\OneDrive\Desktop\Ecommerce-Sales-Profitability-Analysis"

# Create the raw data folder
raw_path = os.path.join(project_path, "data", "raw")
os.makedirs(raw_path, exist_ok=True)

# Copy the original CSV into the project
source_path = r"C:\Users\ASUS\Downloads\ecommerce_orders_dataset.csv"
destination_path = os.path.join(raw_path, "ecommerce_orders_dataset.csv")

shutil.copy2(source_path, destination_path)

print("CSV copied successfully!")

CSV copied successfully!

In [13]:


df = pd.read_csv(
    r"C:\Users\ASUS\OneDrive\Desktop\Ecommerce-Sales-Profitability-Analysis\data\raw\ecommerce_orders_dataset.csv"
)

df.head()

,Order_ID,Customer_ID,Order_Date,Year,Month,Day,Day_Of_Week,Quarter,Customer_Age,Customer_Gender,...,Delivery_Days,Order_Status,Returned,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount,Season,Holiday_Season,High_Value_Order
0,615717,CUST007322,2023-01-01,2023,1,1,Sunday,1,32,Male,...,2,Delivered,No,4.4,2144.92,23.10,15.75,Winter,No,No
1,626919,CUST004717,2023-01-01,2023,1,1,Sunday,1,50,Male,...,9,Delivered,No,4.1,817.17,8.57,3.32,Winter,No,No
2,615781,CUST004415,2023-01-01,2023,1,1,Sunday,1,61,Male,...,2,Delivered,No,5.0,541.16,29.72,45.67,Winter,No,No
3,621747,CUST004114,2023-01-01,2023,1,1,Sunday,1,34,Male,...,6,Returned,Yes,3.4,700.49,25.22,75.25,Winter,No,No
4,625881,CUST000145,2023-01-01,2023,1,1,Sunday,1,37,Male,...,8,Delivered,No,3.6,2133.77,24.64,26.06,Winter,No,No

In [14]:
# df=pd.read_csv(r"C:\Users\ASUS\Downloads\ecommerce_orders_dataset.csv")

In [15]:
df.head()

,Order_ID,Customer_ID,Order_Date,Year,Month,Day,Day_Of_Week,Quarter,Customer_Age,Customer_Gender,...,Delivery_Days,Order_Status,Returned,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount,Season,Holiday_Season,High_Value_Order
0,615717,CUST007322,2023-01-01,2023,1,1,Sunday,1,32,Male,...,2,Delivered,No,4.4,2144.92,23.10,15.75,Winter,No,No
1,626919,CUST004717,2023-01-01,2023,1,1,Sunday,1,50,Male,...,9,Delivered,No,4.1,817.17,8.57,3.32,Winter,No,No
2,615781,CUST004415,2023-01-01,2023,1,1,Sunday,1,61,Male,...,2,Delivered,No,5.0,541.16,29.72,45.67,Winter,No,No
3,621747,CUST004114,2023-01-01,2023,1,1,Sunday,1,34,Male,...,6,Returned,Yes,3.4,700.49,25.22,75.25,Winter,No,No
4,625881,CUST000145,2023-01-01,2023,1,1,Sunday,1,37,Male,...,8,Delivered,No,3.6,2133.77,24.64,26.06,Winter,No,No

In [16]:
df.tail()

,Order_ID,Customer_ID,Order_Date,Year,Month,Day,Day_Of_Week,Quarter,Customer_Age,Customer_Gender,...,Delivery_Days,Order_Status,Returned,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount,Season,Holiday_Season,High_Value_Order
29995,603016,CUST006407,2026-12-31,2026,12,31,Thursday,4,28,Female,...,7,Delivered,No,4.4,4656.30,36.51,118.72,Winter,Yes,No
29996,615920,CUST003743,2026-12-31,2026,12,31,Thursday,4,49,Female,...,7,Delivered,No,4.6,3748.59,15.93,31.71,Winter,No,No
29997,603150,CUST005027,2026-12-31,2026,12,31,Thursday,4,41,Male,...,8,Shipped,No,4.1,1726.84,26.93,27.46,Winter,Yes,No
29998,626020,CUST008716,2026-12-31,2026,12,31,Thursday,4,38,Male,...,3,Delivered,No,3.8,2519.08,11.30,29.61,Winter,Yes,No
29999,609440,CUST009000,2026-12-31,2026,12,31,Thursday,4,18,Male,...,4,Shipped,No,3.4,2238.12,39.60,62.87,Winter,Yes,No

In [17]:
df.shape

(30000, 41)

In [18]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Order_Date', 'Year', 'Month', 'Day',
       'Day_Of_Week', 'Quarter', 'Customer_Age', 'Customer_Gender', 'Country',
       'City', 'Customer_Segment', 'Product_ID', 'Product_Category',
       'Product_Subcategory', 'Brand', 'Unit_Price', 'Quantity',
       'Discount_Percent', 'Discount_Amount', 'Coupon_Used', 'Shipping_Cost',
       'Tax_Amount', 'Order_Amount', 'Payment_Method', 'Device_Type',
       'Traffic_Source', 'Membership_Status', 'Shipping_Method',
       'Warehouse_Region', 'Delivery_Days', 'Order_Status', 'Returned',
       'Review_Rating', 'Customer_Lifetime_Value', 'Profit_Margin_Percent',
       'Profit_Amount', 'Season', 'Holiday_Season', 'High_Value_Order'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Order_ID                 30000 non-null  int64
 1   Customer_ID              30000 non-null  object
 2   Order_Date               30000 non-null  object
 3   Year                     30000 non-null  int64
 4   Month                    30000 non-null  int64
 5   Day                      30000 non-null  int64
 6   Day_Of_Week              30000 non-null  object
 7   Quarter                  30000 non-null  int64
 8   Customer_Age             30000 non-null  int64
 9   Customer_Gender          30000 non-null  object
 10  Country                  30000 non-null  object
 11  City                     30000 non-null  object
 12  Customer_Segment         30000 non-null  object
 13  Product_ID               30000 non-null  object
 14  Product_Category         30000 non-null  object
 15  Product_Subcategory      30000 non-null  object
 16  Brand                    30000 non-null  object
 17  Unit_Price               30000 non-null  float64
 18  Quantity                 30000 non-null  int64
 19  Discount_Percent         30000 non-null  int64
 20  Discount_Amount          30000 non-null  float64
 21  Coupon_Used              30000 non-null  object
 22  Shipping_Cost            30000 non-null  float64
 23  Tax_Amount               30000 non-null  float64
 24  Order_Amount             30000 non-null  float64
 25  Payment_Method           30000 non-null  object
 26  Device_Type              30000 non-null  object
 27  Traffic_Source           30000 non-null  object
 28  Membership_Status        30000 non-null  object
 29  Shipping_Method          30000 non-null  object
 30  Warehouse_Region         30000 non-null  object
 31  Delivery_Days            30000 non-null  int64
 32  Order_Status             30000 non-null  object
 33  Returned                 30000 non-null  object
 34  Review_Rating            30000 non-null  float64
 35  Customer_Lifetime_Value  30000 non-null  float64
 36  Profit_Margin_Percent    30000 non-null  float64
 37  Profit_Amount            30000 non-null  float64
 38  Season                   30000 non-null  object
 39  Holiday_Season           30000 non-null  object
 40  High_Value_Order         30000 non-null  object
dtypes: float64(9), int64(9), object(23)
memory usage: 9.4+ MB

In [20]:
df.describe()

,Order_ID,Year,Month,Day,Quarter,Customer_Age,Unit_Price,Quantity,Discount_Percent,Discount_Amount,Shipping_Cost,Tax_Amount,Order_Amount,Delivery_Days,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,615000.500000,2024.494700,6.531500,15.723600,2.507000,36.370300,126.820148,3.080667,12.618667,49.432742,10.316779,29.143818,379.001466,4.436667,4.047990,4372.340178,21.969056,73.863876
std,8660.398374,1.118815,3.460955,8.779714,1.118806,11.315534,172.675272,1.450412,11.085201,114.401634,5.890701,49.562251,585.405554,2.349363,0.686492,6811.029394,9.079134,113.480736
min,600001.000000,2023.000000,1.000000,1.000000,1.000000,18.000000,3.840000,1.000000,0.000000,0.000000,0.000000,0.260000,6.670000,0.000000,1.000000,20.000000,3.000000,0.270000
25%,607500.750000,2023.000000,4.000000,8.000000,2.000000,28.000000,29.880000,2.000000,0.000000,0.000000,6.020000,5.270000,82.947500,3.000000,3.600000,1029.637500,15.680000,16.640000
50%,615000.500000,2024.000000,7.000000,16.000000,3.000000,36.000000,60.670000,3.000000,10.000000,13.470000,9.000000,12.065000,171.030000,4.000000,4.100000,2073.365000,21.870000,36.995000
75%,622500.250000,2025.000000,10.000000,23.000000,4.000000,44.000000,128.572500,4.000000,20.000000,44.822500,14.220000,29.442500,388.190000,6.000000,4.600000,4482.105000,28.180000,82.125000
max,630000.000000,2026.000000,12.000000,31.000000,4.000000,75.000000,1940.000000,11.000000,40.000000,2623.900000,32.600000,1043.160000,10314.270000,13.000000,5.000000,50000.000000,56.610000,2480.540000

In [21]:
df.describe(include="all")

,Order_ID,Customer_ID,Order_Date,Year,Month,Day,Day_Of_Week,Quarter,Customer_Age,Customer_Gender,...,Delivery_Days,Order_Status,Returned,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount,Season,Holiday_Season,High_Value_Order
count,30000.000000,30000,30000,30000.000000,30000.000000,30000.000000,30000,30000.000000,30000.000000,30000,...,30000.000000,30000,30000,30000.000000,30000.000000,30000.000000,30000.000000,30000,30000,30000
unique,NaN,8683,1461,NaN,NaN,NaN,7,NaN,NaN,3,...,NaN,5,2,NaN,NaN,NaN,NaN,4,2,2
top,NaN,CUST000031,2024-03-09,NaN,NaN,NaN,Monday,NaN,NaN,Female,...,NaN,Delivered,No,NaN,NaN,NaN,NaN,Summer,No,No
freq,NaN,14,39,NaN,NaN,NaN,4327,NaN,NaN,14863,...,NaN,19497,26967,NaN,NaN,NaN,NaN,7575,25550,22499
mean,615000.500000,NaN,NaN,2024.494700,6.531500,15.723600,NaN,2.507000,36.370300,NaN,...,4.436667,NaN,NaN,4.047990,4372.340178,21.969056,73.863876,NaN,NaN,NaN
std,8660.398374,NaN,NaN,1.118815,3.460955,8.779714,NaN,1.118806,11.315534,NaN,...,2.349363,NaN,NaN,0.686492,6811.029394,9.079134,113.480736,NaN,NaN,NaN
min,600001.000000,NaN,NaN,2023.000000,1.000000,1.000000,NaN,1.000000,18.000000,NaN,...,0.000000,NaN,NaN,1.000000,20.000000,3.000000,0.270000,NaN,NaN,NaN
25%,607500.750000,NaN,NaN,2023.000000,4.000000,8.000000,NaN,2.000000,28.000000,NaN,...,3.000000,NaN,NaN,3.600000,1029.637500,15.680000,16.640000,NaN,NaN,NaN
50%,615000.500000,NaN,NaN,2024.000000,7.000000,16.000000,NaN,3.000000,36.000000,NaN,...,4.000000,NaN,NaN,4.100000,2073.365000,21.870000,36.995000,NaN,NaN,NaN
75%,622500.250000,NaN,NaN,2025.000000,10.000000,23.000000,NaN,4.000000,44.000000,NaN,...,6.000000,NaN,NaN,4.600000,4482.105000,28.180000,82.125000,NaN,NaN,NaN
max,630000.000000,NaN,NaN,2026.000000,12.000000,31.000000,NaN,4.000000,75.000000,NaN,...,13.000000,NaN,NaN,5.000000,50000.000000,56.610000,2480.540000,NaN,NaN,NaN

In [22]:
df.isnull().sum()

Order_ID                   0
Customer_ID                0
Order_Date                 0
Year                       0
Month                      0
Day                        0
Day_Of_Week                0
Quarter                    0
Customer_Age               0
Customer_Gender            0
Country                    0
City                       0
Customer_Segment           0
Product_ID                 0
Product_Category           0
Product_Subcategory        0
Brand                      0
Unit_Price                 0
Quantity                   0
Discount_Percent           0
Discount_Amount            0
Coupon_Used                0
Shipping_Cost              0
Tax_Amount                 0
Order_Amount               0
Payment_Method             0
Device_Type                0
Traffic_Source             0
Membership_Status          0
Shipping_Method            0
Warehouse_Region           0
Delivery_Days              0
Order_Status               0
Returned                   0
Review_Rating              0
Customer_Lifetime_Value    0
Profit_Margin_Percent      0
Profit_Amount              0
Season                     0
Holiday_Season             0
High_Value_Order           0
dtype: int64

In [23]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

Order_ID                   0.0
Coupon_Used                0.0
Tax_Amount                 0.0
Order_Amount               0.0
Payment_Method             0.0
Device_Type                0.0
Traffic_Source             0.0
Membership_Status          0.0
Shipping_Method            0.0
Warehouse_Region           0.0
Delivery_Days              0.0
Order_Status               0.0
Returned                   0.0
Review_Rating              0.0
Customer_Lifetime_Value    0.0
Profit_Margin_Percent      0.0
Profit_Amount              0.0
Season                     0.0
Holiday_Season             0.0
Shipping_Cost              0.0
Discount_Amount            0.0
Customer_ID                0.0
Discount_Percent           0.0
Order_Date                 0.0
Year                       0.0
Month                      0.0
Day                        0.0
Day_Of_Week                0.0
Quarter                    0.0
Customer_Age               0.0
Customer_Gender            0.0
Country                    0.0
City                       0.0
Customer_Segment           0.0
Product_ID                 0.0
Product_Category           0.0
Product_Subcategory        0.0
Brand                      0.0
Unit_Price                 0.0
Quantity                   0.0
High_Value_Order           0.0
dtype: float64

In [24]:
df.duplicated().sum()

0